language: cpp

compiler:
  - gcc
  - clang

sudo: required
dist: trusty

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt56-trusty -y; fi
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq qt56base
  - source /opt/qt56/bin/qt56-env.sh
  - sudo apt-get install cmake
  - sudo apt-get install libopencv-dev

before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug ..

script: make

notifications:
    email:
      - romain.goffe@gmail.com
    on_success: change
    on_failure: always
