 language: cpp

 compiler:
   - gcc
   - clang

 before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake qt5-default qttools5-dev-tools libopencv-dev

 before_script:
   - mkdir build
   - cd build
   - cmake ..

 script: make

 notifications:
   email:
     - romain.goffe@gmail.com
   on_success: change
   on_failure: always
